Hw05 avatars
dev-kucha/goit-node-hw-rest-api pull request #4
Opened 2022-11-20 21:44 UTC by dev-kucha

Ready for review

2022-11-21 16:04 UTC, Eastvarga commented on controllers/avatars.controller.js
> +  const newAvatarPath = `${destination}/${name}-${nanoid(6)}.${extention}`;
Невірний url 'D:\\GoIt_Homeworks\\HW_02\\yuriy-kucher\\public\\avatars/my photo mini-noQwQk.jpg'
Вірний  url  http://localhost:3000/avatars/my%20photo%20mini-noQwQk.jpg

2022-11-21 16:05 UTC, Eastvarga requested changes
Є велике зауваження.

2022-11-22 19:32 UTC, dev-kucha commented on controllers/avatars.controller.js
> +  const newAvatarPath = `${destination}/${name}-${nanoid(6)}.${extention}`;
Дякую. Пофіксив

2022-11-25 22:57 UTC, Eastvarga requested changes
Приберіть теку localhost:3000/avatars
 її ім'я блочить фетчинг репозіторію
 Не треба в репозіторій зберігати непотріб (всі ці зображення результат тесту, а не частина коду). Треба зберігати чистоту

2022-11-26 14:51 UTC, dev-kucha commented
Дякую. Трохи почистив сміття, прибрав зайву папку.

2022-11-26 16:43 UTC, Eastvarga commented on controllers/avatars.controller.js
> +  const newAvatarPath = path.join(req.headers.host, "/avatars/", newAvatarName);
Невірно!
Що таке URL, а що таке path? Яким чином вони у Вас пересіклися у едину логіку?
Не можна оперувати поняттями файлової системи при намаганнях згенерувати чи створити лінк до файлу
`${HOST}/avatars/${fileName}`

2022-11-26 16:45 UTC, Eastvarga requested changes
Невірна строка URL

2022-11-26 17:32 UTC, dev-kucha commented on controllers/avatars.controller.js
> +  const newAvatarPath = path.join(req.headers.host, "/avatars/", newAvatarName);
Прибрав path, додав протокол.

2022-11-26 18:01 UTC, Eastvarga approved these changes

2022-11-26 18:01 UTC, merged