Hw06 email
dev-kucha/goit-node-hw-rest-api pull request #5
Opened 2022-11-30 18:34 UTC by dev-kucha

Ready for review

2022-11-30 20:30 UTC, Eastvarga requested changes
Є зауваження

2022-11-30 20:30 UTC, Eastvarga commented on controllers/auth.controller.js
> +    from: "ukucher@gmail.com",
Пошта відправника теж конфігураційний параметр - або у конфігах або у змінних середовища повинна бути

2022-11-30 20:30 UTC, Eastvarga commented on controllers/auth.controller.js
> +  const validationUrl = `http://localhost:3000/api/users/verify/${verificationToken}`;
localhost:3000 - це хост сервера - теж конфігураційний параметр

2022-11-30 20:30 UTC, Eastvarga commented on routes/api/auth.router.js
> +authRouter.post("/verify/", tryCatchWrapper(requestEnotherVerifyController));
/verify/  зайвий слеш

2022-11-30 20:30 UTC, Eastvarga commented on service/authService.js
>  const login = async (email, password) => {
Не виконано завдання ДЗ - поки юзер не веріфікувався - його логін блокується

2022-12-01 16:51 UTC, dev-kucha commented on service/authService.js
>  const login = async (email, password) => {
Дякую, забув, пофіксив

2022-12-01 16:53 UTC, dev-kucha commented on routes/api/auth.router.js
> +authRouter.post("/verify/", tryCatchWrapper(requestEnotherVerifyController));
Видалив

2022-12-01 17:03 UTC, dev-kucha commented on controllers/auth.controller.js
> +    from: "ukucher@gmail.com",
Згоден. Пофіксив

2022-12-01 17:03 UTC, dev-kucha commented on controllers/auth.controller.js
> +  const validationUrl = `http://localhost:3000/api/users/verify/${verificationToken}`;
Також пофіксив. Дякую!

2022-12-01 20:02 UTC, Eastvarga approved these changes

2022-12-01 20:02 UTC, merged